### ISSUE TITLE
Formatting is wrong, action still passes

### ISSUE THREAD

**Issue by RomeoAva** [ChartBoost/ruff-action#11]
Hi, I am a new user to Ruff (transitioning from Black).
I am trying to setup this action on my repo to have the same functionalities I had with Black.

For example: 

```python
app = FastAPI(
    title="API",
    description="API",
    version="0.0.1",terms_of_service="https://example.com/",
)
```

With this code block, the formatting is wrong, it should be

```python
app = FastAPI(
    title="API",
    description="API",
    version="0.0.1",
    terms_of_service="https://example.com/"
)
```
And this is indeed fixed once I do the command `ruff format app/main.py`.

But when opening a pull request, ruff-action doesnt seem to mind that formatting mistake. How could I make it more strict in this sense to enforce the code formatting rules? 

Here is my action:

```
name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
```

Thank you for your help
