### ISSUE TITLE
adding changed-files: 'true' fails

### ISSUE THREAD

**Issue by ingjulioreyes** [ChartBoost/ruff-action#27]
Hi,

I'm using this config:

```
- name: Ruff lint
  continue-on-error: true
  uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 #https://github.com/ChartBoost/ruff-action/releases/tag/v1
    with:
      src: './scripts'
      args: 'format --check'
      changed-files: 'true'
```

But when running the action shows:
```
Warning: Unexpected input(s) 'changed-files', valid inputs are ['args', 'src', 'version']
Run chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4
  with:
    src: ./scripts
    args: format --check
    changed-files: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
```

Any advice on how to proceed? Thanks!
