### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pipx'

### ISSUE THREAD

**Issue by johanneszellinger** [ChartBoost/ruff-action#4]
I have the following workflow yml:

```
name: Code Checking

on:
  workflow_dispatch:
  pull_request:


jobs:
  code-analysis:
    name: Code analysis, linting, pytest
    runs-on: [ self-hosted ]
    permissions:
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install project and dependencies
        run: |
          pip install mydependencypackage/.
          pip install mypythonproject/.

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
```

Which will lead to the following error:

> Run if [ "$RUNNER_OS" == "Windows" ]; then
> Traceback (most recent call last):
>   File "/home/larry/actions-runner/_work/_actions/chartboost/ruff-action/v1/action/main.py", line 23, in <module>
>     proc = run(["pipx", "run", req, *shlex.split(ARGS), *shlex.split(SRC)])
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/larry/actions-runner/_work/_tool/Python/3.11.4/x64/lib/python3.11/subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/larry/actions-runner/_work/_tool/Python/3.11.4/x64/lib/python3.11/subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/home/larry/actions-runner/_work/_tool/Python/3.11.4/x64/lib/python3.11/subprocess.py", line 1950, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'pipx'
> Error: Process completed with exit code 1.

Which seems to be fixed by changing the step before running ruff to 

```
      - name: Install project and dependencies
        run: |
          pip install mydependencypackage/.
          pip install mypythonproject/.
          pip install pipx
```

Not sure if I even should install pipx, but in any case, shouldn't the whole setup be done by the github action anyway?
Apart from that the action seems to run perfectly fine (it fails telling me about all my code issues :D ).
