### ISSUE TITLE
Pulling ruff version from requirements.txt file

### ISSUE THREAD

**Issue by alichaudry** [ChartBoost/ruff-action#5]
Hello, is there a way to pull the ruff version to be used from a specific requirements.txt (or pyproject.toml) file? Currently I have to hardcode the ruff version in two locations to get this to work, but it would be nice to keep the ruff-action version in sync with what's being used in the Python develop/build manifest.

Or if there are other workflows to solve for this problem that I may not have considered, happy to try those out as well.

Cheers!

**Comment by brycedrennan** [comment]
here you go
```yaml
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract ruff version from requirements.txt
        id: ruff_version
        run: echo "::set-output name=version::$(grep -oP 'ruff==\K[^"]+' requirements.txt)"
      - uses: chartboost/ruff-action@v1
        with:
          args: --config tests/ruff.toml
          version: ${{ steps.ruff_version.outputs.version }}
 ```
