### ISSUE TITLE
Add problem matcher

### ISSUE THREAD

**Issue by tobiasdiez** [ChartBoost/ruff-action#7]
With [problem matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md), errors are directly shown in the diff. Would be nice if the action could integrate them directly.

See https://github.com/home-assistant/core/blob/dev/.github/workflows/matchers/ruff.json and the slightly improved https://github.com/sagemath/sage/blob/fd04e63981e1377a5cd7d3d54a48dff543d637c0/.github/workflows/ruff-problem-matcher.json for an example.

**Comment by brucearctor** [comment]
@tobiasdiez -- any interest in contributing this? That'd be welcomed

**Comment by tobiasdiez** [comment]
@brucearctor Interest yes, but I don't have the time right now to read into how github actions work/are developed. But let me know if you want me to help with implementing/testing the actual problem matchers.

**Comment by brucearctor** [comment]
Cool -- this isn't something I can prioritize as work anytime soon...  But, seems quite interesting, so perhaps something for me on night/weekend [ though also, contributions/collaborations welcomed from anyone! ]

**Comment by WieeRd** [comment]
There is no need for a problem matcher!

Ruff already provides [`--output-format`] option/flag, which can be set to `"github"`.
This will produce an output compatible with GitHub's [workflow command] for creating annotations.

```yaml
name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: check --output-format github

```

This is all I've got in my workflow, and it does show annotations in the CI run details tab.


[`--output-format`]: https://docs.astral.sh/ruff/settings/#output-format
[workflow command]: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-creating-an-annotation-for-an-error
