### ISSUE TITLE
Provide api wrapping the cli args

### ISSUE THREAD

**Issue by tobiasdiez** [ChartBoost/ruff-action#8]
It would be nice if common command line args could be directly exposed from the action so that one can use something like
```yml
- uses: chartboost/ruff-action@v1
  with:
     - exclude: |
          E101
          F202
```
instead of providing it manually via `args`

(array input for exclude would also make sense but is not yet implemented: https://github.com/actions/toolkit/issues/184)
